lib/devstates.js

Depends on [https://github.com/Koenkk/zigbee-shepherd-converters/pull/185](https://github.com/Koenkk/zigbee-shepherd-converters/pull/185)
Added state to write occupancy_pirOToUDelay attribute. (tested for hue SML001)
This is sensors timeout between "last motion detected" and sensor reports "occupancy false".

Added occupancy_pirOToUDelay state

---

lib/devstates.js
lib/zigbeecontroller.js
main.js
package.json

Dropped linkedStates from OSRAM devices cause they were causing too much errors.
Instead read command are introduced, which are executed after level has been set to synchronize
state "state" with internal zigbee device state ON or OFF.

Use readAfter states for reading values after main changes

---

lib/zigbeecontroller.js
package.json

@kirovilya 
I'm not so familar with queues and callback and so on. I had an issue when queue is enabled, then the commands are processed at once.
In example I started 100 time the "color" request to a lamp. That leads to 100 calls, several errors and after 30 seconds several timeouts occured. Also my lamp did a hard reset with fallback to factor settings (which then contained an older firmware; which was on the lamp at manufacture date).
I then reset the lamp manually, updated a new firmware via OSRAM gateway and then paired it again with the zigbee stick.
Now I restarted the test with the fixed queue; then also some errors occured, but the lamp didn't reset itself. When a timeout occured then you can see that directly in the log, but then the queued commands are processed further on.
So …

Fixed queue handling

---

README.md

Documentation has been moved to https://koenkk.github.io/zigbee2mqtt/

Chang from wiki link for zigbee2mqtt

---

main.js

Object changes are triggered too often without reason.
This change should limit object changes triggered by calls whithin update_state() only when there is a difference for any property of common object.

avoid unnecessary object changes

---

admin/admin.js
main.js

As of now, devices got only configured (bind, reporting in shepherd-converter) right after adapter start. It it failed for a device for some reason (mesh not ready, too much network load,...), this device stayed without config. Same with newly paired devices, it needed an adapter restart to make them fully work.
Changes in this PR:
- if device config fails, it will be tried again every 5 minutes
- configuration scheduled for newly and re-joined devices
- first configuration starts 30 seconds after adapter start (may help a bit to reduce network load on adapter start)

Device configuration

---

lib/devstates.js

This fixes the tint remote (see #221) on/off not working due to the change made in #247. 
It is fixed by introducing a new state specifically for the tint remote.

Fixed tint remote onOff state

---

package.json

removes nodejs 4 which is not supported here

Upgrade serialport to 7.1.5

---

io-package.json

Fixes the problem
Error: EPERM: operation not permitted, unlink 'C:\ioBroker\[<folder>]\node_modules\iobroker.zigbee\node_modules.serialport.DELETE\build\Release\serialport.node'
when updating running zigbee-adapter with admin.

Fix for install error if running zigbee-adapter is updated

---

.eslintignore
.eslintrc.json
.travis.yml
package.json

To maintain some code quality of PR's, we should have some lint checks, similar to shepherd-converter.
That implementation will check only changed lines. Else we would have lot's of errors on existing code.

Added lint checks to travis runs

---

lib/zigbeecontroller.js

device.getEndpoint need a number, but ep is a string.
Need map string ep to ep number firstly, then call device.getEndpoint
Without this patch, some device which has multiple writeable endpoints can not work.
For example lumi.relay.c2acn01
Signed-off-by: SchumyHao <schumyhaojl@126.com>

fix map endpoints can not work issue

---

admin/admin.js
admin/index_m.html
lib/developer.js
lib/zigbeecontroller.js

Adjusted device-card info page and DeveloperTab to herdsman changes. Both working again.
- Attribute-type input removed (auto-detected)
- Needs https://github.com/Koenkk/zigbee-herdsman/pull/114 for full functionality, but may be merged already (result log messages incomplete only)
(Great job guys! I was very hesitant to switch to herdsman, because with last shepherd version, my smarthome stuff was stable for the first time. But herdsman seems to work stable as well :-) Thanks!)

Device-Info page and Developer-Tab fixed

---

main.js

If there are new states in converter for existing devices, they did not become visible.
Update states list on adapter start (same as we had it on shepherd version already)

Update states list on adapter start

---

lib/devstates.js
main.js

**meta.states**:
Some converter require states object in meta argument (`converter.convertSet(target, key, preparedValue, meta)`)
(like [here](https://github.com/Koenkk/zigbee-herdsman-converters/blob/72619c327da0429b6916dc248df5e9c6a371a5ef/converters/toZigbee.js#L840)
`const currentHostFlags = meta.state.eurotronic_host_flags ? meta.state.eurotronic_host_flags : {}`)
Added
```
if (preparedOptions.hasOwnProperty('state')) {
meta.state = preparedOptions.state;
}
```
so we can return whatever is needed in setterOpt.
**eurotronic_host_flags** 
Added newly available settings as states (already in selected herdsman-converter)
Also added missing setpoint states
_Ready to merge from my side_

Meta.states and eurotronic_host_flags added

---

lib/devices.js

Added Support for Hornbach FLAIR Viyu Smarte LED Lampe RGB E27
Please also add the following image to img:

Hornbach FLAIR LED

---

lib/devices.js

Moved  'TRADFRI bulb E27 WS opal 1000lm' to correct model (the state is lightStatesWithColortemp)

Change: Model 'TRADFRI bulb E27 WS opal 1000lm'

---

lib/devices.js
lib/states.js

This pull request adds three subsequent data points regarding the Philips Hue Smart Button ROM001 to the ioBroker object tree, without changing any of the existing data points:
* `button_press`: The Smart Button is pressed.
* `button_hold`: The Smart Button is still hold down. This event is repeated as long as the button is pressed.
* `button_release`: This event is emitted after each `button_press` event and immediately after releasing a "hold".
These raw events were not supported yet but are required to react to a fast series of button press events. If the button is pressed in a very fast series, no events are generated but only a final high-level action event "on" or "off" is emitted. Thus, it is not possible to rotate through a set of light scenes using very fast button presses, such …

Added missing raw button events for Philips Hue Smart Button ROM001

---

lib/statescontroller.js

Native part is mandatory.
If objects do not exists, they will be created by extendObject, but extendObject will not add native part.
No native part creates some issues, for example with iot Adapter not usable and so on.
What makes issues worse: Admin adapter adds an empty "native"-Part in RAW editor, so the issue is hard to detect.

be sure to have native part on every object

---

lib/states.js

This pull request addresses [issue 600](https://github.com/ioBroker/ioBroker.zigbee/issues/600). It fixes the equations for mapping between adaptor brightness levels [0...100] and bulb brightness levels [0...254].
- An adaptor brightness level of "0" is converted into bulb brightness level "0"
- An adaptor brightness level of "1" is converted into bulb brightness level "1"
- An adaptor brightness level of "100" is converted into bulb brightness level "254"
- A bulb brightness level of "0" is converted into adaptor brightness level "0"
- A bulb brightness level of "1" is converted into adaptor brightness level "1"
- A bulb brightness level of "254" is converted into adaptor brightness level "100"

Fixed mapping of brightness ranges

---

lib/devices.js

As innr RB 248-T bulbs and Paulmann 500.48 did not work as expected, I analyzed the problem and did the following:
- corrected typo for RB 248 T
- add missing device 500.48
Now both kinds of device work fine.

correct typo for innr light and add Paulmann 500.48

---

main.js

Controller connect though WiFi.
Unlikely USB dongle, connection broken may only caused user unpluged the
dongle, WiFi connected gateway is possible that device connection is
broken caused by AP issue or Zigbee gateway power is turned off
unexpectedly. So try to reconnect gateway every 10 seconds all the time.
Signed-off-by: SchumyHao <schumyhaojl@126.com>

Retry reconnect gateway all the time for tcp connected gateway

---

main.js

As initial example taken usage system logger inside the converters in 
`meta.logger.info('ZNCLDJ11LM ' + (opts.hand_open ? 'enabling' : 'disabling') + ' hand open');`
There is [current link](https://github.com/Koenkk/zigbee-herdsman-converters/blob/7b769ef58f3667fec6691c14b071932c92037eb5/converters/toZigbee.js#L1162).
As I can uderstand - it's work with z2m.
But - it can work with iobroker.zigbee too
At least it works witn fromZigbee converters for sure ...
For example:
`if (meta.logger) meta.logger.debug(`lumi.plug.mmeu01: Xiaomi struct: recorded index ${index} with value ${value}`);`

possibility to use iobroker logger in code of the converters, via meta.logger

---

lib/devices.js

Taking in account the approprite accepted [pull request](https://github.com/Koenkk/zigbee-herdsman-converters/pull/1318) to zigbee-herdsman-converters, we have possibility to show the additional state for lumi.plug.mmeu01 devices - i.e. tje load current in A.

add state of current load (A) for lumi.plug.mmeu01

---

admin/admin.js
lib/developer.js
lib/zigbeecontroller.js

Re-implemented Zigbee status codes (UNSUPPORTED_ATTRIBUTE,...) in DeveloperTab log view, since functionality is available now in herdsman.

Improved DeveloperTab logs

---

lib/states.js
lib/utils.js

This pull request is a follow-up to [this bug](https://github.com/ioBroker/ioBroker.zigbee/issues/600). My first pull request made it into the repository but it seems that it was incomplete:
- Thanks to the research of "allofmex" we know now that there are certain "bulb levels" that are "forbidden values" according to the ZigBee specification.
- However, there seem to be IKEA bulbs that require a value of "0" to switch them off.
- The former pull request introduced a regression that HUE bulbs can not be dimmed down to adapter level "1" anymore; they switch off instead.
This pull requests changes the mapping of levels again:
- Bulb levels "0" and "1" (of 254) are both considered as "off", and to switch a bulb off, bulb level "0" is sent.
- Bulb levels [2...254] are mapped to adapter levels …

Fixed the mapping between bulb levels and adapter levels.

---

admin/admin.js
admin/index_m.html
admin/words.js
lib/binding.js
lib/zigbeecontroller.js

RWL021 (Hue Dimmer Switch) needs to be unbound from Coordinator in order to work correctly with binding. If that is not done (before!) binding, it will go into a state where it will only show a red LED and never send any commands anywhere anymore and will not react to anything. Only reset & repair will help, then.
So I added an option to unbind a device from coordinator before adding the binding. 
This is how I got bingdings with this remote get to work in zigbee2mqtt (and there is an issue there describing that problem with the same switch, see https://github.com/Koenkk/zigbee2mqtt/issues/2100 for example.)
Of course, without the binding to the coordinator, the coordinator won't see the commands send and won't know the state of the bulb in the end. So we'd either need reporting (which …

Make bindings work with RWL021

---

lib/devices.js

This adds the Blaupunkt blind/shutter controller according to #580 
It's already included in herdsman converters.

Update with Blaupunkt blind controller

---

lib/devices.js
lib/states.js

The current implementation for the Paulmann 500.67 remote control does not allow to distinguish between groups.  The remote control has three group keys which allows to control three different devices. The currently selected group key is provided with the "action_group" property on each command. 
My suggested change will provide a state "action_group" which has the value of this group, e.g. 1, 2 or 3.

Added action_group state to Paulmann remote control 500.67

---

lib/devices.js

Tested with E1524 and E1810. Some Devices showed the battery state immediately, Some had to reset and re paired. The states apeard after some hours

Added battery state for Tradfri E1524/E1810

---

admin/i18n/de/translations.json

Removed a duplicate entry and removed a comma.
Please ensure your JSON files are valid (e.g. with a linter or https://jsonlint.com/) after a merge. These two issues prevent Weblate from working properly.

Fixed German translations JSON

---

lib/devices.js
lib/states.js

I got the alert siren for Bitron AV2010/24A working.
It could work for Bitron 902010/24 too, but I do not have this device so I cannot test this.
Should close #794

added alert siren for Bitron AV2010/24A

---

admin/admin.js
lib/devices.js
lib/states.js

- news state "interlock" as boolean
- used state in Xiaomi LLKZMK11LM (Response to Issue #887 
- fix device listing for devices with malformed groups
Note: Expose was evaluated and discarded - no expose available for "interlock" in the converters. No expose expected due to rarity of the functionality

Add "interlock" capability to Xiaomi LLKZMK11LM

---

lib/devices.js
lib/states.js

moved to statedefs used in expose
fixed tuya_trv_lock state to be read/write and actually work
removed child_lock due to conflict with tuya_trv_lock
changed from states.voltage to heimann_batt_low

Fix for Tuya Thermostat TS0601

---

lib/devices.js

It must be sent mired to device not kelvin

corrected Gardenpole RGBW-Lightify (4058075036147)

---

admin/admin.js
admin/index_m.html
lib/commands.js
lib/devices.js
lib/states.js
lib/statescontroller.js
lib/zbDeviceAvailability.js
lib/zigbeecontroller.js
main.js

- Modification on 'failed ping' messages
- New state for each device: Device query as button. Activation triggers a 'convertGet' for each converter which has one. 'Spam' protection limits activation to once every 10 seconds. **Note** Use of this may generate warning messages for cases where a state receives an object which is not parsed in a getter.
- Orphaned state removal: 4th button on the top right: Refresh icon. Can be used to remove any state which is no longer linked to the model definition. Does exclude 'groups' and  the states defined as commonstates (available, link_quality, device_query). Default will not delete any state which has a custom configuration (history, etc.) The force checkbox will override this.
- Ping timeout no longer fixed at 5 minutes: Time between pings for a …

Device Query / Orphaned States

---

lib/statescontroller.js

Setting the new state 'debugmessages' to the IEEE of a device (or part of it), the adapter will elevate messages when changing states or receiving zigbee messages to "warn" level, so they can be read in the log without enabling adapter wide debug
this can be changed while the adapter is running.

device specific message capture

---

lib/states.js
lib/statescontroller.js
main.js

Introduce a message function which can be called using the sendTo command from ioBroker user scripts.
Syntax: 
sendTo('zigbee.0', 'SendToDevice', {'device':'bc33acfffe5ec8bb', 'payload':{'brightness_move':10}}, function(res) {
if (res.success) console.log("success") else console.log(res.error);
});
This will offer access to a number of device specific configurations (e.g. "remember_state" on Osram bulbs, "brightness_move" on most bulbs, etc.)
Only functions which are made available through converters at specific devices are supported.

Support extended functionality of zigbee-herdsman-converters without state

---

main.js

For example, an error triggers a workflow that I have to handle actively.
And therefore I feel an "Unsupported Attribute" for an error overrated.
What is your opinion about this?

"Unnsupported Attribute" downgraded from error to warn event

---

.github/workflows/test-and-release.yml

To make the CI tests working, as the **master** branch of JS-Controller is hardcoded it _ioBroker/testing_, and has new dependency, which exclude node 10.x
And node 16.x test is added  for the future compatibility.

Change CI matrix for node - exclude 10.x, as the support is dropped by ioBroker.js-controller (newest version 3.4.0 => 4.0.0)

---

lib/devices.js
lib/states.js

It has object construction in `herdsman-converters`
```
options {
reverse_direction: boolean,
hand_open: boolean,
reset_limits: boolean
}
```
as for fromZigbee, as for toZigbee ...
So, we need to process it as object in both cases - for getter ans setter.
`reset_limits` isn't returned, and marked as Event and button.
Appropriate request for the herdsman-converters to make an exposes in upcoming.

Added processing xiaomi curtains options (reverse_direction, hand_open, reset_limits)

---

lib/exposes.js

Initial idea of this PR is was processing a composite exposes.
The first attempt was made for ZNCLDJ11LM/ZNCLDJ12LM, to make the exposes, which can be processed by 
appropriate converters `fz.xiaomi_curtain_options` and `tz.xiaomi_curtain_options`
After reading the documentation I made it like
```
exposes.composite('options', 'options')
.withDescription('test')
.withFeature(exposes.binary('reset_limits', ea.SET, true, false).withDescription('Reset limits'))
.withFeature(exposes.binary('reverse_direction', ea.SET, true, false).withDescription('Reverse direction'))
.withFeature(exposes.binary('hand_open', ea.STATE_SET, true, false).withDescription('Hand open')),
```
But it wan't generate and process appropriate objects ...
for `toZigbee` converter it have to make in `setter` the value equal …

Exposes composite enchancements

---

lib/exposes.js

A change in exposes and a change in the way certain states are handled as composite exposes in the zigbee-herdsman-converters is causing color values to become read only and unable to set properly from ioBroker. This is caused by the access property of a composite expose not being initialised correctly if the composite expose leads to a single state in ioBroker.
A more generalised fix will be needed in the future to ensure that state access rights and parameters in iobroker are not overwritten unless the state was created via an expose. 
This fix merely grants full access to any state where the expose does not seem to provide any access definition.

Quick Fix: Expose Access Handling

---

lib/developer.js
lib/zigbeecontroller.js

added support for Command Response needed to support IAS ACE cluster security devices.
The changes should be fully backward compatible.
Changes are accessible via an extension to the sendToZigbee interface in iobroker javascripts. a new cmdType "functionalResp" has been added [funtionalfunctionaResp|foundation] in addition a new optional parameter "zclSeqNum" has been added.
See following example:
sendTo("zigbee.0", "sendToZigbee", { "id": senderId, "ep": "1", "cid": "ssIasAce", "cmd": "armRsp", "cmdType": "functionalResp", "zclSeqNum": msg_rcvd.meta.zclTransactionSequenceNumber, "zclData": {"armnotification": msg_rcvd.data.armmode} });
These changes help to support zigbee security devices according to the IAS ACE Cluster. Please see …

Feature: CMD Response Support added

---

lib/exposes.js

For ColorTemperature cannot be found an converter, if device has multiple endpoints. setattr was missing with name "color_temp". This small change fixes the issue.

add setattr for color_temp

---

.github/workflows/test-and-release.yml

This PR add the testing actions to standard worklow. They seem to got lost in the past.
This fault was detected due to the fact that a faulty code could pass into release 1.18.17 and lates repository.
@arteck 
Please review and merge - or adapt testing if this has been blocked by purpose.

Correct adapter tests - they got lost somehow

---

admin/admin.js
admin/index.html
admin/index_m.html
admin/tab_m.html
io-package.json
lib/zigbeecontroller.js

It was quite annoying for me that already paired devices often showed up in the iobroker log with a warning "Device '0x00178801021390b1' announced itself". This happens especially with Philips Hue motion detectors with multiple warnings each day. 
So I added a option to disable the logging on warn level on Zigbee device announcements.

Added a option to disable the logging on warn level on device announcements

---

admin/admin.js

Hello team,
Currently 1 broken device card can prevent the FW Update Check for all other devices, only due to .split(".") being called on devId undefined.
My PR prevents this, by both skipping devices without id-attr in the loop and additionally only resolving the devId on available feedback message.
Thanks and best regards
Thiemo

Skip faulty device cards on fw update check

---

lib/exposes.js
lib/statescontroller.js
lib/utils.js
lib/zbDeviceAvailability.js
lib/zbDeviceConfigure.js
lib/zigbeecontroller.js
main.js
package.json

Bump zigbee-herdsman-converters to 16.6.0
Fix compatibility with new herdsman
Change devices.find to findByModel
Change order of key evaluation in publishFromState and prioritize prop and id before setattr (Fix for tuya thermostat properties)

Bump zigbee-herdsman to 0.26.1

---

lib/commands.js
lib/statescontroller.js
lib/zigbeecontroller.js
main.js

Fix group member display
Fix group delete
Fix device delete
Fix group member edit
Fix crash on channel scan. Note; Channel scan still defunct, but no longer crashes the adapter

Fixes for Herdsman 2.x.x

---

lib/statescontroller.js
main.js

- Change in selection of key for converter (needed forAqara T1M (CL-L02D), Issue #2321)
- Updated logging for debug logs

Fix for Lumi Lamp

---

README.md
io-package.json
lib/devices.js
lib/statescontroller.js
main.js
package-lock.json
package.json

Push version
Fix Linter errors

Version 1.10.14

---

lib/binding.js
lib/commands.js
lib/groups.js
lib/statescontroller.js
lib/zbDeviceAvailability.js
lib/zigbeecontroller.js
main.js

Fix battery status for Ikea Parasoll Devices
Fix random crashes due to unhandled promise rejection (I hope I caught them all now)

Bug and device fix

---

lib/zbDeviceConfigure.js

my SOMRIG button always failed manual reconfiguration with a `Failed to configure. --> definition.endpoint is not a function` so I investigated and compared with zigbee2mqtt which didn't have that problem.
turns out there was a weird `this` instead of a `mappedDevice`.
with my fix my SOMRIG button suddenly started working and now sends button events to iobroker.
I assume this might effect a few other configuration issues with various devices, for me only SOMRIG had these issues, but then again all my other devices were paired and configured when I moved to iobroker.zigbee 2.x, so it might not have applied.

fixed broken configure parameter
