- lib/devstates.js
> new hue devices

- lib/devstates.js
- main.js
- package.json
other xiami devices name for switch WXKG11LM
> lumi.remote.bxxxxx

- lib/devstates.js
> neg contact

- lib/devstates.js
smoke detect corr
alternative battery state add
new hue lamps
> any corrections

- admin/admin.js
- admin/index_m.html
- lib/zigbeecontroller.js
- main.js
First: Thank you very much for this adapter!
I created a new tab in adapter settings to provide a tool for debugging and extending of functionality.
I would be happy if you include it in your adapter. Translations are not included yet. I'll add this later, wanted to await some feedback first.
This is my very first pull request. Feedback welcome :-)
Thanks again
> New settings tab 'Developer'

- main.js
Fix bug when terminating adapter (see issue #200 )
> Bugfix: Adapter lässt sich nicht beenden

- lib/devstates.js
- main.js
Innr RB 285 C Integration
Fix for Bug which keeps new states from being added to states.
> Innr RB285C, Bugfix

- main.js
Suggest. Changes still in discussion https://github.com/ioBroker/ioBroker.zigbee/issues/252
Features:
- first config run for all devices 30 sec after adapter started
- **(NEW)** also a config try will run immediately after a new device (re)joins, the new device will be handled first (should be still awake)
- in case config failed, a new try is scheduled in 5 minutes (maybe done earlier in case new device joins)
> Improved device configuration

- lib/statescontroller.js
Signed-off-by: SchumyHao <schumyhaojl@126.com>
> Fix uncaught exception: adapter is not defined

- lib/devstates.js
TRADFRI bulb E27 WW 806lm
RB 148 T
> new deices

- lib/devices.js
Hello,
I added the Heiman Smokesensor 3.0
Best regards,
Jan
> Added Heimann SmokeSensor-N-3.0

- lib/devices.js
> New devices

- admin/admin.js
- admin/index_m.html
- lib/developer.js
- lib/ota.js
- main.js
Added firmware update functionality.
Very similar to zigbee2mqtt. 
Progress shows in logs.
I successfully updated to of my Hue GU10 bulbs.
(Only "issue" is that device-info page does not update after update finished, you have to reload page to see new buildId.)
> Ota firmware updates

- lib/devices.js
- lib/states.js
Fixes the circle button & "hold" functionality of the Osram switch mini
(Issue #219 and [iobroker forum entry](https://forum.iobroker.net/topic/21381/problem-osram-smart-mini-switch-schaltet-am-zigbee-coordinator-vorbei-fehlende-werte-bei-objekten/23))
> Improvements Osram switch mini

- lib/devices.js
> Fix Color for Outdoor Lantern W RGBW OSRAM

- lib/devices.js
> New version of Nue / 3A inline switch

- lib/devices.js
Got nice wall switch from Gledopto and integrated it.
> Added Gledopto Wall switch

- lib/devices.js
Added Lonhonso 3-button switch (Lerlink X703A) model id
> Added Lonhonso 3-button switch (Lerlink X703A) model id to devices.js

- lib/devices.js
- lib/states.js
More Information in https://forum.iobroker.net/topic/28602/zigbee-neue-unbekannte-ger%C3%A4te-ab-1-0-0/285
> Support for 6735/6736/6737 - Busch-Jaeger RM01

- lib/devices.js
Fixed WXKG11LM as for issue https://github.com/ioBroker/ioBroker.zigbee/issues/699
Added INNR RB 278 T (Successor of RB 178 T)
> Fixed WXKG11LM and added RB 278 T

- lib/devices.js
Include this panel according to #581
> Updated with Osram/Ledvance Panel TW Z3

- lib/devices.js
I extended my devices.js, the LED band was detected and I can control it.
> Added LEDVANCE Smart+ LED Stripe [4058075208339]

- admin/i18n/de/translations.json
> Fixed JSON syntax error

- admin/i18n/de/translations.json
Sorry, typed a semicolon instead of a comma!
> Fixed again syntax

- lib/devices.js
Fixes #832
It's working fine for me.
Unfortunately, I don't know whether I should extend the linkedStates attribute as well.
> Add white endpoint to Mega23M12

- lib/exposes.js
- lib/states.js
- lib/utils.js
Added new setter to ColorTemp which can handle Kelvin and Mired
> add setter to state and exposes ColorTemp

- package.json
Update zigbee-herdsman-converters to v14.0.14
Update zigbee-herdsman to v0.13.50
> Update herdsman version (bugfixes)

- .github/workflows/test-and-release.yml
- README.md
- package-lock.json
- package.json
add .github/workflows/test-and-release.yml 
Please consider to : 
- remove travis from current testing automation
- activate NPM publish in workflow [see here](https://github.com/AlCalzone/release-script/blob/master/README.md)
> Add GitHub workflow for testing & release automation

- lib/devices.js
Added openlumi.gw_router.jn5169
> Added GWRJN5169

- lib/devices.js
https://github.com/ioBroker/ioBroker.zigbee/issues/971
> Fix for Image 9290012573A

- lib/devices.js
Added button_8 to FreePad_LeTV_8
LeTV 8key FreePad mod](https://modkam.ru/?p=1791)
> Added button_8 to FreePad_LeTV_8

- main.js
> improve robustness if config.external does not exists

- admin/admin.js
- package.json
Devices with 'undefined' type caused an exception in admin js.
> Fix for missing device display with broken devices

- lib/states.js
Make reset_limits more manageable and visible, as it has to be true i…n only specific situations.
I,e, button and isEvent is removed.
> HotFix fro Added processing xiaomi curtains options (reverse_direction, hand_open, reset_limits) 

- admin/admin.js
- admin/index_m.html
- admin/tab_m.html
- lib/commands.js
- lib/statescontroller.js
- lib/zbDeviceAvailability.js
- lib/zigbeecontroller.js
- Added button to "deactivate" a device
- deactivated Devices will not be pinged
- deactivated devices do not react to state changes
- deactivated devices show limited info on the cards.
Notes: 
- reactivating devices does not trigger pings to the devices.
> Device Deactivation

- lib/ota.js
Block Firmware Update for devices which are
- disabled through the UI
- marked unavailable (available=false)
- have a recorded LQI of 0
reference issue #653
> Block OTA for disabled devices

- lib/devices.js
AC0251100NJ/AC0251700NJ -> AC0251100NJ/AC0251600NJ/AC0251700NJ
> Update name of attribute 'models' for Osram Switch Mini

- admin/admin.js
- admin/index_m.html
- lib/zbDeviceAvailability.js
- main.js
state available is green colored and not available is red
you can set it on adapter settings 
p.s: know issue -> dark mode is buggy
> color devices in objectlist dependent on status

- lib/exposes.js
See https://github.com/ioBroker/ioBroker.zigbee/pull/1433#issuecomment-1113837035 and https://github.com/ioBroker/ioBroker.zigbee/issues/1432#issuecomment-1113849730
> Explicitly ignore min and max color temperature

- admin/admin.js
See https://github.com/ioBroker/ioBroker.zigbee/issues/1432#issuecomment-1113961184
> Set color temperature slider value range to 150..500 mireds

- README.md
Update README.md Silicon Labs and ZiGate info
> Update README.md Silabs and ZiGate info

- admin/admin.js
> #1549 spz0001 doesn't acknowledge the change to spz trv mode

- lib/zbDeviceConfigure.js
added this as logger to device.configure
> fixes adapter crashes for certain devices by adding a logger argument to device.configure.

- io-package.json
> io-package.json: remove installedFrom (Error reported by adapter Checker)

- main.js
closes https://github.com/ioBroker/ioBroker.zigbee/issues/1799
> Fix syntax error (#1799)

- main.js
Fix wrong level type in sending a error message to sentry.
> Fix send sentry error

- lib/developer.js
- lib/zigbeecontroller.js
Fix Developer Tab to changes in zigbee-herdsman
> Fix Developer Tab

- admin/admin.js
- admin/index_m.html
- admin/tab_m.html
The system for displaying the group assignment had a bug which made it work for devices with 4 or fewer eligible endpoints, but not above. This limit has been raised to 6 eligible endpoints.
A.
> Fix Name change / Group assignment

- admin/admin.js
Sort entries of the rooms dropdown. Otherwise, with a large enough list, it becomes cumbersome to find a specific room.
> Sort rooms

- lib/statescontroller.js
fix indentation of axios change in #2203 to make linter happy.
the whole CI should be green after this change.
> fix indent of axios.

- package-lock.json
- package.json
> Bump Herdsman

- admin/admin.js
- lib/zigbeecontroller.js
Fix for scanning channel energy
> Fix channel scan

- main.js
Added a fix to handling keyless converters to ensure that it does not matter at which index of the converter array the keyless converter is found.
> Fix keyless converters

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/iobroker/Dockerfile
- .devcontainer/iobroker/boot.sh
- .devcontainer/iobroker/node-wrapper.sh
- .devcontainer/nginx/nginx.conf
- .devcontainer/scripts/postcreate.sh
- .devcontainer/scripts/postcreate_ext.sh
- .devcontainer/scripts/poststart.sh
- .devcontainer/scripts/wait_for_iobroker.sh
- .gitignore
- .vscode/launch.json
1) Open project in vscode (`code .`)
2) Modify `.devcontainer/scripts/postcreate_ext.sh` according to your zigbee coordinator
3) Click or call command "Reopen in Dev Container"
4) Press F5 for starting debugging
> Add Dev Container support

- package.json
> ZHC 24.8.0
